move env to args

diff --git a/charts/akeyless-api-gateway/templates/cache.yaml b/charts/akeyless-api-gateway/templates/cache.yaml
--- a/charts/akeyless-api-gateway/templates/cache.yaml
+++ b/charts/akeyless-api-gateway/templates/cache.yaml
@@ -36,7 +36,37 @@ spec:
       - name: {{ $deploymentName }}
         image: "{{ .Values.cache.image.repository }}:{{ .Values.cache.image.tag }}"
         imagePullPolicy: {{ .Values.cache.image.pullPolicy }}
-        #args: ["--requirepass", "$(REDIS_PASSWORD)"]
+        args:
+        - redis-server
+        - --requirepass
+        - $(REDIS_PASSWORD)
+        - --rename-command
+        - FLUSHDB
+        - ""
+        - --rename-command
+        - FLUSHALL
+        - ""
+        - --maxmemory
+        - {{ include "akeyless-api-gw.redisMaxmemory" . | quote }}
+        - --maxmemory-policy
+        - allkeys-lru
+        {{- if (include "cacheEnableTls" . | eq "true") }}
+        - --port
+        - "0"
+        - --tls-port
+        - "6379"
+        - --tls-auth-clients
+        - "yes"
+        - --tls-cert-file
+        - {{ $tlsCertPath }}
+        - --tls-key-file
+        - {{ $tlsCertKeyPath }}
+        - --tls-ca-cert-file
+        - {{ $tlsCACertPath }}
+        {{- else }}
+        - --port
+        - "6379"
+        {{- end }}
         ports:
         - containerPort: 6379
           name: cache
@@ -45,23 +75,22 @@ spec:
             command:
             - sh
             - -c
-            - |            
+            - |
                 #!/usr/bin/env bash -e
-                export REDISCLI_AUTH="$REDIS_PASSWORD"
                 set_response=$(
-                  redis-cli {{ $tlsArgs }} set liveness_test_key "SUCCESS"
+                  redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" set liveness_test_key "SUCCESS"
                 )
                 response=$(
-                  redis-cli {{ $tlsArgs }} get liveness_test_key
+                  redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" get liveness_test_key
                 )
                 del_response=$(
-                  redis-cli {{ $tlsArgs }} del liveness_test_key
+                  redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" del liveness_test_key
                 )
                 if [ "$response" != "SUCCESS" ] ; then
                   echo "Unable to get keys, something is wrong"
                   echo "$response"
                   exit 1
-                fi               
+                fi
           initialDelaySeconds: 5
           periodSeconds: 5
         readinessProbe:
@@ -69,50 +98,26 @@ spec:
             command:
             - sh
             - -c
-            - |            
-              #!/usr/bin/env bash -e
-              export REDISCLI_AUTH="$REDIS_PASSWORD"
-              response=$(
-                redis-cli {{ $tlsArgs }} ping
-              )
-              if [ "$response" != "PONG" ] ; then
-                  echo "Unable to get keys, something is wrong"
-                  echo "$response"
-                  exit 1
-              fi
+            - |
+                #!/usr/bin/env bash -e
+                response=$(
+                  redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" ping
+                )
+                if [ "$response" != "PONG" ] ; then
+                    echo "Unable to get keys, something is wrong"
+                    echo "$response"
+                    exit 1
+                fi
           initialDelaySeconds: 5
           periodSeconds: 5
         resources:
           {{- toYaml .Values.cache.resources | nindent 12 }}
         env:
-        - name: REDIS_DISABLE_COMMANDS
-          value: "FLUSHDB,FLUSHALL"
-        - name: REDIS_EXTRA_FLAGS
-          value: '--maxmemory {{ include "akeyless-api-gw.redisMaxmemory" . }} --maxmemory-policy allkeys-lru'
         - name: REDIS_PASSWORD
           valueFrom:
             secretKeyRef:
               name: {{ include "akeyless-api-gw.cacheSecretName" . }}
               key: cache-pass
-        - name: REDIS_TLS_ENABLED
-          value: {{ include "cacheEnableTls" . | quote -}}
-        {{- if (include "cacheEnableTls" . | eq "true") }}
-        - name: REDIS_TLS_PORT
-          value: "6379"
-        - name: REDIS_PORT
-          value: "2001"
-        - name: REDIS_TLS_AUTH_CLIENTS
-          value: "yes"
-        - name:  REDIS_TLS_CERT_FILE
-          value: {{ $tlsCertPath }}
-        - name:  REDIS_TLS_KEY_FILE
-          value: {{ $tlsCertKeyPath }}
-        - name:  REDIS_TLS_CA_FILE
-          value: {{ $tlsCACertPath }}
-        {{ else }}
-        - name: REDIS_PORT
-          value: "6379"
-        {{- end }}
         {{- if (include "cacheEnableTls" . | eq "true") }}
         volumeMounts:
         - name: cache-tls
diff --git a/charts/akeyless-secure-remote-access/templates/redisStorage.yaml b/charts/akeyless-secure-remote-access/templates/redisStorage.yaml
--- a/charts/akeyless-secure-remote-access/templates/redisStorage.yaml
+++ b/charts/akeyless-secure-remote-access/templates/redisStorage.yaml
@@ -30,22 +30,21 @@ spec:
                 - sh
                 - -c
                 - |
-                  #!/usr/bin/env bash -e
-                  export REDISCLI_AUTH="$REDIS_PASSWORD"
-                  set_response=$(
-                    redis-cli set liveness_test_key "SUCCESS"
-                  )
-                  response=$(
-                    redis-cli get liveness_test_key
-                  )
-                  del_response=$(
-                      redis-cli del liveness_test_key
-                  )
-                  if [ "$response" != "SUCCESS" ] ; then
-                    echo "Unable to get keys, something is wrong"
-                    echo "$response"
-                    exit 1
-                  fi
+                    #!/usr/bin/env bash -e
+                    set_response=$(
+                      redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" set liveness_test_key "SUCCESS"
+                    )
+                    response=$(
+                      redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" get liveness_test_key
+                    )
+                    del_response=$(
+                      redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" del liveness_test_key
+                    )
+                    if [ "$response" != "SUCCESS" ] ; then
+                      echo "Unable to get keys, something is wrong"
+                      echo "$response"
+                      exit 1
+                    fi
             initialDelaySeconds: 5
             periodSeconds: 5
           readinessProbe:
@@ -54,15 +53,14 @@ spec:
                 - sh
                 - -c
                 - |
-                  #!/usr/bin/env bash -e
-                  export REDISCLI_AUTH="$REDIS_PASSWORD"
-                  response=$(
-                      redis-cli ping
-                  )
-                  if [ "$response" != "PONG" ] ; then
-                      echo "Unable to get keys, something is wrong"
-                      echo "$response"
-                      exit 1
+                    #!/usr/bin/env bash -e
+                    response=$(
+                      redis-cli {{ $tlsArgs }} -a "$REDIS_PASSWORD" ping
+                    )
+                    if [ "$response" != "PONG" ] ; then
+                        echo "Unable to get keys, something is wrong"
+                        echo "$response"
+                        exit 1
                     fi
             initialDelaySeconds: 5
             periodSeconds: 5
